#!/bin/bash
# hlds_run.sh - ReHLDS Installation Script for Debian/Ubuntu
# Version: 31 Aug 2025

# Change script name self to avoid confusion
if [ -f hlds_run ]; then
    echo "Renaming hlds_run to hlds_run_tmp.sh"
    mv hlds_run hlds_run_tmp.sh
    clear
fi

# Welcome meessage

echo "  ____________   _____      _           _ _     _   __        ";
echo " |___  /  ____| |  __ \    | |         (_) |   | | /_ |       ";
echo "    / /| |__    | |__) |___| |__  _   _ _| | __| |  | | __  __";
echo "   / / |  __|   |  _  // _ \ '_ \| | | | | |/ _\` |  | | \ \/ /";
echo "  / /__| |____  | | \ \  __/ |_) | |_| | | | (_| |  | |_ >  < ";
echo " /_____|______| |_|  \_\___|_.__/ \__,_|_|_|\__,_|  |_(_)_/\_\\";
echo "                                                              ";
echo "                                                              ";
echo "ReHLDS Installation Script for Debian/Ubuntu";
echo "Package Version: 31 Aug 2025";
echo "Welcome to the ReHLDS installation script!"
echo "--------------------------------------------------------------"

# Download the rehlds_pack tar file
wget https://github.com/z0h1r-LK/ze-rehlds_pack/releases/download/31-08-25/rehlds_full.tar -O rehlds_full.tar

# Extract the downloaded tar file
if [ ! -f rehlds_full.tar ]; then
    echo "Download failed. Please check your internet connection or the URL."
    exit 1
fi

# Extract the tar file
echo "Extracting files..."
tar -xf rehlds_full.tar

if [ $? -ne 0 ]; then
    echo "Extraction failed. Please check the tar file."
    exit 1
fi

# Delete the tar file after extraction
echo "Cleaning up..."
rm -rf rehlds_full.tar
sleep 1

# Give permissions to the hlds_run.sh file
chmod +x hlds_run
chmod +x hlds_linux
chmod +x hltv

# Done
rm -rf hlds_run_tmp.sh
echo "Installation complete. You can now run the server now, If doesn't work try again many times!"
exit 1